apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        kubernetes dev.local {
            pods insecure
            upstream /etc/resolv.conf
            fallthrough
        }
        proxy cluster.local 192.168.0.10:53
        proxy . /etc/resolv.conf
        cache 30
    }
kind: ConfigMap
metadata:
  labels:
    addonmanager.kubernetes.io/mode: EnsureExists
  name: coredns
  namespace: kube-system
